### ISSUE TITLE
Components

### ISSUE THREAD

**Issue by manuel-rubio** [kevinlang/bulma-elixir#3]
This library is very useful to grasp the assets for Bulma, but it could also be great to cover the core components based on the components, elements, and other facilities that Bulma gives us.

Just as an example:

```elixir
defmodule Bulma.Components do

  slot :item, required: true do
    attr :href, :string
    attr :active, :boolean, default: false
    slot :inner_block, required: true
  end

  def breadcrumb(assigns) do
    ~H"""
    <nav class="breadcrumb" aria-label="breadcrumbs">
      <ul>
        <%= render_slot(@item) %>
      </ul>
    </nav>
    """
  end
end
```

This way we could use Bulma with the Elixir facilities.

**Comment by suranyami** [comment]
@manuel-rubio You probably want to check out the fork I made of `bulma_components`:

https://github.com/suranyami/bulma_components

It started off with a tiny implementation by the original author, but I've been working on adding everything that Phoenix needs for `CoreComponents`, and I hope to add all of Burma's functionality as part of it.

I could do with some help getting a final version released, so feel free to join in! 😄 

I get the feeling that neither @kevinlang or @mcrumm (original author of `bulma_components`) have the bandwidth to continue maintaining these, so, if I don't hear back in a while, I think it's gonna be easier to just rename them both and re-release both `bulma-elixir` and `bulma_components`.

**Comment by manuel-rubio** [comment]
@suranyami I checked it out some time ago, it looked like a work in progress and there is a lot to be done yet to get it working. At this moment, I'm not sure if it's better to start from scratch, I did an adaptation in my accounting platform, you can check it out here:

https://github.com/altenwald/conta/blob/main/apps/conta_web/lib/conta_web/components/core_components.ex

**Comment by suranyami** [comment]
@manuel-rubio You checked out the original `bulma_components` or my fork?

We seem to have done a lot of the same work, hence my suggestions above. In particular, I've recently been adding as much detail as I can and about to start on docs and website for it.

**Comment by manuel-rubio** [comment]
@suranyami Yes, but we ended with a different code, I prefer to have something more similar to the original `CoreComponents` from Phoenix but using Bulma rather than needing to redesign everything.

**Comment by manuel-rubio** [comment]
I think DaisyUI is doing a great job and looks like it's the way the community is following so I close this.
